CodeforAustralia/council-emissions-calculator

README.md

Just making the getting started steps clearer for first timers :)

added install step to getting started

---

next.config.js

reference docs:
- https://wallis.dev/blog/next-js-basepath-and-assetprefix
- https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix

use relative path for assetPrefix

---

pages/form/Question4.js

[Trello card](https://trello.com/c/Wv2qDZ21/167-dev-sml-update-page-4-of-form-to-reflect-updated-wireframe)
Quick work using the approved pages as template code!
@batteries76 @hqtan The spacing is off on all the pages we've made progress on so far. Would it be okay to address this for all 5 pages in a separate Trello card?

form page 4

---

components/FormProvider/FormProvider.jsx
pages/form/Question2.js
pages/results.js
utils/constants.js

A decision was made on the list of transport mode choices to use in Question 2 of form ('How do you travel to work in an average week?')
See this [trello card](https://trello.com/c/a9ZvQGNu) for details
This PR updates the transport mode choices used in form to align with decision
**N.B:** the [`calculateEmissions` function](https://github.com/CodeforAustralia/council-emissions-calculator-spike/blob/main/utils/calculateEmissions.js) is broken due to the changes made to the transport mode data collected in Question 2. This will be addressed on a different PR

Update transport modes

---

pages/form/Question1.jsx

Question 1 Next button was enabled before required answer was given. 
Fixed in this PR!

fix Q1 Next button always enabled

---

pages/form/Thankyou.jsx

Thank You page: 
- closed top gap by ~30%
- added "safe to close tab" message to bottom of text

Thank You page adjustments

---

components/DaysOfTheWeek/DayOfTheWeekButton.jsx
components/DaysOfTheWeek/DaysOfTheWeekContainer.jsx
pages/form/DaysOfTheWeekSelection.jsx

* re-factoring (remove a separate state for active/inactive "save" button, make saveDataAndShowLog a formula, pass number of days from child to parent, etc)
* changed button from "save" to "next" as per design;
* "Back" link is now directing to "/form/WorkArrangement";

Component updates - daysOfTheWeek (page, container, button)

---

utils/constants.js

Order of the Travel button position and text(request for change) is updated matching figma. 
- Utils/constant file modeOfTransport is the only component object changed.
If this can be reviewed and merged ASAP it will be helpful for the next task where I have to check for specific button selection text. Thank you

Travel button text change

---

components/DaysOfTheWeek/DayOfTheWeekButton.jsx

Edited this component to match with figma. This is Child component of #89.
- The width is set for desktop and mobile version . 
- The font on button is set to matched with figma design.

Changed the text on button to match with figma design .

---

pages/form/Suggestions.jsx
public/images/progress-bar/q7-progress-dots.svg

Changes from original version:
* User can no longer resize the box;
* Word council is no longer capital
* The Next button is disabled unless User inputs a number;
* Once user clicks Next - he/she will be directed to Department page;
* Once user clicks Back - he/she will be directed to Distance page;
[click here](https://trello.com/c/vUuhcx61)
- Manual testing.

add Suggestions page to the survey with updated logic and style

---

pages/form/WorkFromHomeDays.jsx
pages/form/WorkOnSiteDays.jsx

Add `WorkOnSiteDays` page to the survey, to collect the number of days a council staff member works onsite.
Other minor changes of note in PR:
- also updated text in `WorkFromHomeDays` page to align with Figma designs
- updated 'Next page' links in `WorkFromHomeDays` and `WorkOnSiteDays`, to make it more convenient to test the button selections
https://trello.com/c/m4iduWnH
Instructions to test that the changes in this PR meets the Acceptance Criterias listed in Trello card:
On the `WorkOnSiteDays` page:
- Confirm that The 'Next' button is disabled unless user selects one day.
- Confirm user can select / unselect more than one day
- Confirm that days that have been selected as WFH days should be disabled
- Confirm that once the 'Next' button has been clicked, users' selected days should …

Add `WorkOnSiteDays` page

---

pages/form/TravelMethod.jsx
pages/form/WorkOnSiteDays.jsx

This PR updates the 'Back button' links for `WorkOnSiteDays` and `TravelMethod` pages so that the page sequences align with the 3 work arrangement flows (hybrid, onsite and wfh) as defined in the Figma designs
https://trello.com/c/vOtejFwk
Reviewers should test the survey in the preview deployment up to TravelMethods page to ensure that the Acceptance Criterias listed in the Trello Cards have been addressed.
- when user clicks 'Back' on the `WorkArrangement` page, user should be presented with the Welcome page
- when user clicks 'Back' on the `WorkFromHomeDays` page, user should be presented with `WorkArrangement` page
- when user clicks 'Back' on the `WorkOnSiteDays` page, user should be presented with `WorkFromHomeDays` page
- when user clicks 'Back' on the `TravelMethod` page, user …

Fix back button links for `WorkOnSiteDays` and `TravelMethod` page

---

components/FormProvider/FormProvider.jsx
components/TravelMethodButtons/CarpoolCounter.jsx
components/TravelMethodButtons/TravelMethodButtons.jsx
pages/form/TravelMethod.jsx

This PR introduces some refactoring to `CarpoolCounter` component. 
The primary changes makes the component more 'self-contained'. Specifically, this entails: 
- removing the need to pass in `CarpoolCounter`'s button handlers and count state as props. The button handlers are now defined within the component itself, and the count state is also now managed within component itself.
- The changes also mean that `TravelMethodButtons` no longer needs to be concerned with managing `CarpoolCounter`'s state, and we can remove the props related to `CarpoolCounter` for this component
- The changes also mean that things like `CarpoolCounter`'s button handlers and count state no longer needs to be defined in `TravelMethod` page.  
The reviewer can verify with the preview deployment that the following …

Refactor `CarpoolCounter` component

---

components/FormProvider/FormProvider.jsx
components/TravelDayButtons/TravelDayButton.jsx
components/TravelDayButtons/TravelDayButtonsContainer.jsx
pages/api/sheeter.js
pages/form/TravelDays.jsx
pages/form/TravelMethod.jsx

Add `TravelDays` page (a modified version of `ConfirmWFH` page) to collect the days of travel (using the selected travel methods from `TravelMethod` page) from respondents.
In addition to the `TravelDays` page, the following new components are added to this PR:
- addition of `answers.travelMethodByDay` to collect responses from `TravelDays` page
- `travelMethodByDay` is a JSON object with days of weeks as keys, and travel methods as values. see changes in `components/FormProvider/FormProvider.jsx` for details
- `TravelDayButtonsContainer` component
- a 'container' to hold a collection of 'day of week' `TravelDayButton` buttons for respondent to select, for a particular travel method 
- `TravelDayButton` component
- a component representing an individual button, containing its state, and …

Initial commit of `TravelDays` page

---

components/ConfirmDetailsContainer/ConfirmDetailsContainer.jsx
pages/form/ConfirmWFH.jsx

Demo page to show to the design team tomorrow, not functional.
Please have a look and compare to the picture above. 

Wfh confirm page

---

pages/form/Suggestions.jsx

Remove logit to disable next button for suggestions page.
Fixing the bug.
Click "Next" without adding any text to the text area.

remove logic to disable next button for suggestions page

---

pages/form/Thankyou.jsx

Update content of the thank you page.
Required: 
Now (before changes): 
(https://trello.com/c/DS2GOKNQ)
Visual

Thankyou fix

---

components/TravelDayButtons/TravelDayButtonsContainer.jsx
pages/form/TravelDays.jsx

Selected Travel Method Icon will display on Travel Days selected page.
IMPORTANT 
- ** This PR  focused on only the Icons that should be displayed accordingly. 
https://trello.com/c/2dTPQfGC/315-dev-travel-days-page
- Selected mode of transport  from TravelMethod page should now display has an Icon symbol on TravelDays page.
- Confirm when user change TravelMethod from previous selection then the icons on TravelDays will follow the changes.
- Confirm the icons are same as the selected TravelMethod in name in text.
- 
- [ X] Is your pull request up-to-date with `main` branch?
- [ X] Have you checked That code is well formatted? Did `npx prettier --check .` return no warnings/errors?
- [ X] …

add selected travelmethod icon

---

pages/form/TravelDays.jsx
pages/form/WorkFromHomeDays.jsx
pages/form/WorkOnSiteDays.jsx

update progress bar for WorkOnSiteDays.jsx, WorkFromHomeDays.jsx, TravelDays.jsx
N/A

Progress bar

---

pages/form/WorkArrangement.jsx

Update width of the work-arrangement page

Layout fix for work arrangement

---

pages/form/Department.jsx

Small changes to the layout in accordance with design in Figma:
* remove 'required' text;
* change width of the Submit button to be the same as Select element;
* alter width to match the rest of the pages;
* change progress bar from Q5 to Q8;
* Prettier check and changes.
**Before:**
**Now:** 
* Manual test, resizing the browser window.

Department layout fix

---

components/TravelDayButtons/TravelDayButtonsContainer.jsx
components/TravelMethodButtons/TravelMethodButtons.jsx
pages/form/TravelDays.jsx

Update `TravelDays` page to address remaining Acceptance Criterias in Trello card:
- in `wfh` flow: show only days in `answers.wfhDays`
- in `onsite` & `hybrid` flow: show only days in `answers.onsiteDays`
- disable 'Next' button on `TravelDays` page until following conditions are met:
- when some selections have been made
- when each work day has a travel method associated
- when each travel method have at least a day associated
- update `TravelDay` responses when selected travel methods change
https://trello.com/c/2dTPQfGC/315-dev-travel-days-page
Reviewers to test that the following changes to 'TravelDays' selections work as expected:
- in `wfh` flow: show only days that respondent selected in 'WorkFromHomeDays' page to select from
- in `onsite` and 'hybrid' flow: show only days that …

Update TravelDays page to address ACs 4, 6, 6.1

---

components/TravelMethodButtons/CarpoolCounter.jsx
components/TravelMethodButtons/TravelMethodButtons.jsx
pages/form/TravelMethod.jsx

Add error message to notify user the travel method limit has been reached. 
Browser window.

Travel method error message

---

components/TravelMethodButtons/TravelMethodButtons.jsx

This PR addresses [the feedback about the Travel Method alert description given here](https://codeforaustralia.slack.com/archives/C01CXCQPF8V/p1652069255473219?thread_ts=1652054520.127719&cid=C01CXCQPF8V).
The alert description message needs to make it clear that this refers to on-site working days.
The `<AlertDescription>` text in Travel Method page should be updated to this sentence:
> You can only select as many travel methods as there are days you work on-site

update travel method alert description

---

components/TravelMethodButtons/TravelMethodButton.jsx

This PR updates the hover color for `<TravelMethodButton>` component to:
- provide adequate contrast to discern between a selected and unselected button while hovering over them
- align with `<DayOfTheWeekButton>`'s hover color
https://trello.com/c/z50v3GrA
Reviewers should verify that:
- users viewing the 'TravelMethod' page in a browser on their mobile phone can discern the difference between a selected and unselected travel method button
- when a user uses a mouse to interact with 'TravelMethod' page in a browser:
- when user hovers mouse over an unselected travel method button, button's color **should not** be the same color as a selected travel method button.
- hover color for `<TravelMethodButton>` matches that of `<DayOfTheWeekButton>`'s
Make sure the following checkboxes`[ ]` are …

update hover color for travel method button

---

pages/results.js

This PR is a small change to set up the Results page for upcoming work.
Adds 2 `<Flex>` components to split the page up into left and right columned sections
Page should look something like this:

initial work on results page

---

pages/results.js

1. Provide outline and img for each section as per current design: https://www.figma.com/file/DEa98hc9qYB0meam2wtOau/Delta-D?node-id=1330%3A37203
2. Create a folder for Results page components so we can group them in one place.
* This is a prep work only, no testing, no design.
* IMGs are links to the github screenshot downloads, so no unnecessary imgs in the project folders.
I also disabled `getServerSideProps()` async function for the time being as it caused error due to data coming back as `undefined`.
How it looks:
This is a prep work only, no testing, no design.
- ~[ ] Have you included a link Trello card / Github issue and written sufficient description to help others review your work?~ …

Results outline completed

---

components/TravelMethodButtons/TravelMethodButtons.jsx
pages/form/TravelDays.jsx

- update text in Travel Method page to clarify to respondents to select ALL travel methods that apply
- update text in Travel Days page to add explanation for respondents on how to fill in selections
- ensure Travel Methods page text has been updated to include 'ALL':
- ensure Travel Days page has been updated with following text underneath heading:

add more explanation to text in Travel Method and Travel Days page, as per suggestions from council

---

pages/results.js

I noticed [Figma](https://user-images.githubusercontent.com/88268603/174800922-8b09ebb9-f5b6-4b61-a396-50df26fc3229.png) design has changed:
* One graph was replaced;
* Two graphs were added.
Reflected in the design preview so we don't follow the old design. 
This is a planning task, no tests are required.

Design update

---

components/ResultsPageComponents/WorkArrangement/WorkArrangement.jsx
data/2022-results.json
pages/results.js

Data is now getting populated dynamically from the data file:
Depending on the max. min or medium count - it will be asigned to either the biggest medium or small vector-man.
I tested cases where:
* All 3 numbers are different;
* All 3 numbers are the same;
* 2 numbers are the same and one is different;
In the situation when two numbers are the same: it's either one of them will be the highest and one - medium or one medium and one the lowest. 
~- [ ] Have you included a link Trello card / Github issue and written sufficient description to help others review your work?~

Walking men graph data

---

components/ResultsPageComponents/DownloadResults/DownloadResults.jsx
public/202207_results/20220711_survey_responses.csv

This PR supersedes #171 .
This PR implements the 'download csv' button (see screenshot)
Test in the preview deployment that csv file will either begin downloading, or be prompted where to save csv file, when 'Download survey data' button in clicked.
Verify that the saved file contains the same csv content as the file in `public/202207_results/20220711_survey_responses.csv`

implement csv download button

---

components/ResultsPageComponents/SurveyOverview/SurveyOverview.jsx

Trim average values (`avgDistancePerTrip` & `avgEmissionPerTrip`) to two significant digits:

trim average distance and emissions values to 2 significant digits

---

components/ResultsPageComponents/CommuteDistanceDistribution/CommuteDistanceDistribution.jsx
components/ResultsPageComponents/CommuteDistanceDistribution/CommuteDistanceDistributionChart.jsx

- Edited chart description to match design
- Added "KM" to x-axis values
- Changed y-axis configuration to display 0% to 100%
- Changed chart title to fit colours in design
- Changed bottom description to hide the blue dot and display just the text
- Edited layout to suit mobile view
Mobile view:
Desktop view:

Distribution of Commute Distance chart

---

data/2022-results.json

Change data from numbers to percentage.

change work-mode from numbers to percentage

---

components/ResultsPageComponents/SurveyOverview/SurveyOverview.jsx

This PR updates the text content for the 'Survey Overview' section of the results page, to match the text content set forth in the [final figma design](https://www.figma.com/file/DEa98hc9qYB0meam2wtOau/Delta-D?node-id=2921%3A42965) (see screenshot below):
**N.B:** The Figma design did not give an example where readers could better relate to and understand what the total amount of carbon emissions meant. In the absence of guidance, I chose to use olympic sized swimming pools to help readers understand how much CO2 was emitted by council staff during a week's commute:
> Respondents commuted a total distance of 13921km and a total emission of 2.91t during one week. This is roughly enough CO2 to fill 13 Olympic sized swimming pools. The average distance is 13km per trip, with an average of …

Update survey overview section text

---

components/ResultsPageComponents/TripCountAndTravelMethods/TripCountAndTravelMethods.jsx

This PR updates the text content for the "trip count and travel methods" section of the results page, to match the text content set forth in the [final figma design](https://www.figma.com/file/DEa98hc9qYB0meam2wtOau/Delta-D?node-id=2921%3A42965) (see screenshot below):
Ensure the text in 'trip count and travel methods' section of results page is aligned with figma design:
- font settings has not been changed
- UI layout of this section has not been changed

update text for "trip count and travel methods" section

---

components/ResultsPageComponents/TripCountAndTravelMethods/TripCountAndTravelMethods.jsx

Small fix for the trip count
- [] Have you included a link Trello card / Github issue and written sufficient description to help others review your work?

fix issue with sharedVsIndividualData

---

components/ResultsPageComponents/SurveyIntro/SurveyIntro.jsx

This PR updates the text content for the 'Survey Intro' section of the results page, to match the text content set forth in the [final figma design](https://www.figma.com/file/DEa98hc9qYB0meam2wtOau/Delta-D?node-id=2921%3A42965) (see screenshot below):
Ensure the 'Survey Intro' section of results page is align with figma design:
- font settings has not been changed
- UI layout of this section has not been changed

Update survey intro section text

---

components/ResultsPageComponents/TopThree/TopThreeBarChart.jsx

Replace `T` with `t` as `t` is official symbol for tonnes
[top 3: emissions uses the wrong unit symbol for tonnes](https://trello.com/c/iyBfrBBT/335-top-3-emissions-uses-the-wrong-unit-symbol-for-tonnes)

Tonne refactor

---

pages/howWeCalculate.js

This PR updates the method of calculation in HWC page to reflect the changes in [final design page of Figma for HWC page](https://www.figma.com/file/opEaLsTMNJjhKHx3KNXRe6/How-to-calculate-page-hand-off?node-id=2938%3A34061) (see screenshot):
- check that the HWC page is aligned with design set forth in Figma:
- check that HWC behaves responsively without cropping text on left hand side when viewed on mobile devices:

Update method of calculation in HWC page

---

components/ResultsPageComponents/SurveyIntro/SurveyIntro.jsx

Edited introduction to _Results_ page for grammar
https://trello.com/c/0MPbKRh1/323-results-page-intro-and-overview-grammar
The Introduction section should look like this:

Results page intro

---

components/ResultsPageComponents/SurveyOverview/SurveyOverview.jsx
data/2022-results.json

Edited wording for Overview section for legibility and clarity
The text section for the Overview section should look like this:

Overview section text

---

components/ResultsPageComponents/StaffSuggestions/StaffSuggestions.jsx

This PR updates the 2nd paragraph of 'Staff suggestions' section text
see discussion thread [here](https://codeforaustralia.slack.com/archives/C03JWTLMQ07/p1660795279538889?thread_ts=1660794172.763109&cid=C03JWTLMQ07)
verify text changes are displayed in preview deployment webpage

update 2nd paragraph in staff suggestions section

---

pages/results.js

Match alignment of the first component with the rest of the page.

match alignment for the first component with the rest of the page

---

pages/results.js

put a dot to test deployment

---

pages/results.js

test deployment

---

pages/results.js

remove dot - end of test

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

this PR addresses #225 
PR adds a issue template for bug reports and feature requests

add issue templates for bug reports and feature requests
