scripts/ghpages-deploy.sh

- script previously exits when it tries to rm a non-existent file
- update file to check for non-existent files

fix bug in gh-pages deployment script

---

pages/form/5.js
pages/results.js
utils/dbApi.js

**N.B:**
- the code that implements api for access google sheets (db) isn't in this PR!
- [`utils/dbApi.js:sendFormResponse()`](https://github.com/CodeforAustralia/council-emissions-calculator-spike/compare/main...hqtan:add-api-for-db?expand=1#diff-90ce3c7e3f364a7a3e82f1f527c17b8c6a5fb6115f5def2000809a51fb5b950dR4) submits the JSON data containing form response to api (currently configured as [`http://localhost:8080`](https://github.com/CodeforAustralia/council-emissions-calculator-spike/compare/main...hqtan:add-api-for-db?expand=1#diff-90ce3c7e3f364a7a3e82f1f527c17b8c6a5fb6115f5def2000809a51fb5b950dR1))
-  [`utils/dbApi.js:getFormResponses()`](https://github.com/CodeforAustralia/council-emissions-calculator-spike/compare/main...hqtan:add-api-for-db?expand=1#diff-90ce3c7e3f364a7a3e82f1f527 …

Add functions for submitting and retrieving form responses from google sheets

---

package-lock.json
package.json
pages/api/sheeter.js
utils/dbApi.js

The main purpose of this PR is to add the `sheeter` API route to app, which will be used to access Google Sheets.
- add sheeter api as an API route
see: https://nextjs.org/docs/api-routes/introduction
- updated `utils/dbApi` to use sheeter API route
- add googleapi library in `package.json` for sheeter api route
- update next.js in `package.json` for security updates

add sheeter api to access Google Sheets

---

components/Layout/Layout.jsx
utils/constants.js

This PR fixes a problem with the url of favicon. Currently, url is pointing to [favicon served from github pages](https://codeforaustralia.github.io/council-emissions-calculator-spike/favicon.ico). This should not be. App should use favicon served from current deployment of app.
details of change
- update favicon url to use favicon of current deployment, (and not
favicon from github pages)
- remove `productionUrl` variable declared in `utils/constants.js`; no
longer used; will obtain url of app from `NEXT_PUBLIC_HOST`
environment variable moving forward

update url for favicon

---

pages/form/Question4.jsx
pages/form/Question5.jsx

- alignment is now left
- selected is now bold
- React complaints about the following have been addressed:
- id mismatches between virtual and browser DOM
- prefer `defaultValue` in `select` component to `selected` in `option` element

fix dropdowns from Q4 and Q5

---

components/Layout/Layout.jsx

Fixed some Header layout issues on mobile:
- Added a left-margin on the SeeChange title (for mobile)
- Workaround to center progress bar on mobile

fix Header layout

---

components/TravelMethodButtons/TravelMethodButton.jsx
components/TravelMethodButtons/TravelMethodButtons.jsx

This pull request addressing one of the request in putting from PR 68 to separate the button component .
- The new component "TravelMethodButton" will be rendered in "TravelMethodButttons" .
- 'TravelMethodIcon'  is moved into this new button component . It directly imported into this component .
-  The 'trello' for this task : https://trello.com/c/z50v3GrA/297-dev-travel-method-selection-page
- Please refer to this 'trello' link there is a question need attention to fix the way long text on the button wraps for mobile version. 
ADDITIONAL INFORMATION ****
1. PR68 and PR70 should be reviewed in that order .
2. PR68  should be reviewed first and merge.
3. PR70 to be reviewed and merged after PR68 .

Separate  component  travel button

---

pages/index.js

this PR relates to the [task for 'Work Arrangement' page](https://trello.com/c/uMT9o9s9), implemented in #72 
Depends on #72 
this PR updates link in the Welcome Page's 'Start' button to take user to the `WorkArrangement` page, the first question in the updated Survey flow (see latest [figma design here](https://www.figma.com/file/Y42AKuHDW46LiLDaTOs6sM/Heroes-carbon-calculator-designs?node-id=978%3A55067) 
clicking on the 'Start' button on the [Welcome page](https://github.com/CodeforAustralia/council-emissions-calculator/blob/main/pages/index.js) should lead to the [`WorkArrangement` page](.pages/form/WorkArrangement.jsx), once #72 has been merged into `main` branch

link to `form/workArrangement` for 'Start' button

---

components/DaysOfTheWeek/DaysOfTheWeekContainer.jsx
components/FormProvider/FormProvider.jsx
pages/form/WorkFromHomeDays.jsx

PR addresses [this trello card](https://trello.com/c/KBQFjU1B)
- `setNumberOfDays` from `DaysOfTheWeekContainer` now returns a list of days which user selected as
working from home, instead of returning the number of days worked
- the calculation for number of days worked is now done on `WorkFromHomeDays` page. Calculation done by summing wfh days and onsite days
- added state vars for `wfhDays` and `onsiteDays` in `components/FormProvider/FormProvider.jsx`
- when a user revisits the `WorkFromHomeDays` page (by hitting back button), users' previously selected inputs should be shown. We can't test this just yet (until back link button is updated)

update data model to save wfh days from `WorkFromHomeDays` page

---

pages/form/PageNotFound.jsx
pages/form/WorkArrangement.jsx

Hi team,
* I quickly made a temporary landing page for onSite and Hybrid flows;
* Changed the href for workArrangement page so it leads to the right page and user can see it in the deployed version.

Temporary landing page for onSite and Hybrid flows

---

components/DaysOfTheWeek/DaysOfTheWeekContainer.jsx

This PR introduces a bug fix (or maybe it's an improvement).
It allows for previously saved answers (in `answers.wfhDays` and `answers.onsiteDays`) to display as selected buttons in the `DaysOfTheWeekContainer` component of the `WorkFromHomeDays` page.
When a user revisits the `WorkFromHomeDays` page (by hitting the 'Back' button), user should expect to see their previously selected wfh days on the page.
Instructions for testing this PR works as expected in the preview deployment:
1. go to `form/WorkFromHomeDays` page, make your selection(s), then hit 'Next' button (should currently be taken to `/form/TravelMethod` page)
- confirm that chosen days are logged correctly in logflare
2. go back to `form/WorkFromHomeDays` page (by clicking Back button in browser, or pressing 'Alt+Back' or …

retain selected days in `DaysOfTheWeekContainer` component when revisiting `WorkFromHomeDays` page

---

pages/form/WorkArrangement.jsx
pages/form/WorkFromHomeDays.jsx
pages/form/WorkOnSiteDays.jsx

This PR updates the 'Next button' links for `WorkArrangement`, `WorkFromHomeDays`, and `WorkOnSiteDays` pages so that the page sequences align with the 3 work arrangement flows (`hybrid`, `onsite` and `wfh`) as defined in the Figma designs
https://trello.com/c/vOtejFwk
Reviewers should test the survey in the preview deployment up to `TravelMethods` page to ensure that the Acceptance Criterias listed in the Trello Cards have been addressed.
- user should not be able to proceed to next page unless he/she has made a selection on current page
- when user clicks 'Next' on the `WorkArrangement` page, user should be presented with `WorkFromHomeDays` page
- when user clicks 'Next' on the `WorkFromHomeDays` page, user should be presented with `WorkOnSiteDays` page
- when user clicks 'Next' on the …

Ensure page sequences for `hybrid`, `onsite` and `wfh` work arrangement flows (up to `TravelMethod` page) are correct

---

pages/form/WorkArrangement.jsx

The changes in this PR recalculates the total number of days worked (stored in `answers.numDaysWorked`) in the `WorkArrangement` page
- if a user changes their work arrangement selection (e.g, from `hybrid` to `onsite`), the total number of days worked will need to be recalculated to reflect the new work arrangement selection
- the updated `numDaysWorked` value will also need to be saved to data model (`answers`), and reflected in the log message in logflare
Use logflare to verify that the changes in this PR works as expected:
1. using the preview deployment, fill in the survey (up to `/form/TravelMethod` page) using the following details:
- in `WorkArrangement` page, select '___I work fully from home___', then click 'Next'
- in `WorkFromHomeDays` select 'Monday' and 'Friday', then click …

Fix `numDaysWorked` calculation in `WorkArrangement` page

---

components/FormProvider/FormProvider.jsx
components/TravelMethodButtons/TravelMethodButtons.jsx
pages/form/Question4.jsx
pages/form/TravelMethod.jsx
utils/constants.js

This PR is a small refactor to align on our naming convention, which is to refer to the different transport types as 'Travel Methods'.
This change will avoid confusion in future, and will also make it clear that variable name containing 'TravelMethod' are related to the `TravelMethod` page.
Test using the preview deployment that the changes do not change the current functionality of the app. Compare with the [production deployment](https://council-emissions-calculator-spike-flax.vercel.app) that:
- there are no changes to functionality in 'TravelMethod' page
- there are no changes to the page sequences from the 'Welcome' page to 'TravelMethod' page in all 3 work arrangement flows ('wfh', 'onsite', 'hybrid')
Make sure the following checkboxes`[ ]` are checked with `x` before sending your …

small refactor: rename all references of `modesOfTransport` to `TravelMethods`

---

components/FormProvider/FormProvider.jsx
components/TravelMethodButtons/TravelMethodButton.jsx
components/TravelMethodButtons/TravelMethodButtons.jsx
pages/form/TravelMethod.jsx

This PR will introduce the following changes:
- save responses for `TravelMethod` page (to `answers.travelMethods`)
- refactor `TravelMethodButtons` component:
- handle component's state management within component itself
- buttons' state stored in `travelMethodButtonStates` State hook, managed within component
- define `handleTravelMethodButtonClick` method to deal with button click events and save responses to `answers.travelMethods`, and update `answers.carpoolPassengerCount`
- create `updateCarpoolPassengerCount()` method to update `answers.carpoolPassengerCount` according to the following criterias:
- if `Carpool` is selected, set `carpoolPassengerCount` to 1
- if `Carpool` already selected, do not reinitialise `carpoolPassengerCount` (keep current value)
- if `Carpool` is …

Refactor Travel Method state management

---

pages/form/Department.jsx

Adding the **final** page to survey!
The `Department` page is a copy of `pages/form/Question5.jsx`, with slight modifications.
It collects the respondents department info that they work for.
Reviewers should verify the following in the preview deployment:
- checking that the responses are sent to Google sheets when user clicks 'Submit'. This needs more work, and will be addressed on a separate PR 

add `Department` page

---

pages/form/Distance.jsx

small one-line change for `Distance` page.
when user clicks on `Back` button on `Distance` page, users should be taken to `TravelDays` page
Reviewers should verify on the preview deployment that when user clicks on `Back` button on `Distance` page, users should be taken to `TravelDays` page

fix 'Back' button link on `Distance` page

---

components/TravelMethodButtons/TravelMethodButton.jsx

- This PR made a small change in fixing the `taxi/ride share` text on travelMethod page to be wrapped on mobile version. 
https://trello.com/c/z50v3GrA/297-dev-travel-method-selection-page
- Tested locally and viewed to verify the changes on mobile version. 
- You can view the old version and the preview this changes to see the difference.
- [ x] Have you included a link Trello card / Github issue and written sufficient description to help others review your work?
- [x ] Is your pull request up-to-date with `main` branch?
- [x ] Have you checked That code is well formatted? Did `npx prettier --check .` return no warnings/errors?
- [x ] Have you written instructions on how to test that your …

wrap text for ride share button

---

components/TravelDayButtons/TravelDayButton.jsx
components/TravelDayButtons/TravelDayButtonsContainer.jsx
pages/form/TravelDays.jsx

Working on responsiveness of the page:
* Remove minW and replace with maxContainerWidth;
* Icon and title of each card are center aligned on mobile;
* Link button is 100% width on mobile;
* Day buttons have adjustable width based on the container on re-sizing;
Result below
* Open the page in desktop mode;
* Resize the page;
* Use toggle device toolbar to check mobile version.

Work days layout change for mobile

---

components/TravelMethodButtons/TravelMethodButton.jsx
components/TravelMethodButtons/TravelMethodButtons.jsx

This PR updates the 'Travel Method' survey question to place a limit on the number of travel methods a respondent can select:
- in the 'wfh' flow, that limit is set as the number of wfh days respondent selected in 'WorkFromHomeDays' page
- in the 'hybrid' and 'onsite' flow, that limit is set as the number of onsite days respondent selected in 'WorkOnSiteDays' page
this PR also addresses what happens to travel method selections in the scenario where respondent returns to 'WorkFromHomeDays' or 'WorkOnSiteDays' page to reduce the number of work days selected. 
In that scenario, the respondent's travel method selections will also be reduced accordingly to match the updated work days. 
https://trello.com/c/z50v3GrA
- confirm that respondent can only select (at most) the same number of travel …

[WIP] Add travel method selection limit

---

pages/form/TravelDays.jsx

Change the alert message for travel days so it displays different content based on conditions (examples on screenshots):
**Title:** Incomplete selection (same for both versions.
**Body:**  "Please select a travel method for each work day."
* Some travel methods don't have days: 
* Not all days are selected:
1. Select more days than travel methods;
2. Select one day for each travel method leaving one or more days not selected. See if alert message has changed.

Travel days alert - add an option for the case when not all days are selected

---

components/DaysOfTheWeek/DayOfTheWeekButton.jsx
components/LinkButton/LinkButton.jsx
components/TravelDayButtons/TravelDayButton.jsx
components/TravelMethodButtons/TravelMethodButton.jsx

- remove custom colorscheme and behaviour for disabled buttons
(`DayOfTheWeekButton`s, `LinkButton`s, `TravelDayButton`s and
`TravelMethodButton`)
Reviewers to confirm that:
- the color contrast for disabled `DayOfTheWeekButton` and `TravelDayButton` matches screenshot below:
- the color contrast for disabled `TravelMethodButton` matches screenshot below

remove custom settings for disabled buttons to improve color contrast between button background and text

---

components/DaysOfTheWeek/DaysOfTheWeekContainer.jsx
components/TravelDayButtons/TravelDayButton.jsx

This PR fixes a bug in iOS/Webkit browsers.
Problem: in Webkit browsers, the text labels in the DayOfWeek buttons and TravelDays buttons are surrounded by some whitespaces, causing Day-of-week matching issues in the backend logic.
Fix: use `.trim()` String method to remove any whitespaces from the text labels in the DayOfWeek buttons and TravelDays buttons
- verify that user can select Day of Week buttons in the following pages:
- `WorkFromHomeDays` 
- `WorkOnSiteDays` 
- `TravelDays`
using a iphone browser (safari/chrome/firefox), and an android browser

trim any whitespaces around the text label in the daysOfTheWeek and TravelDayButtons button components

---

components/TravelMethodButtons/TravelMethodButton.jsx

This PR fixes an bug that was observed in iOS/WebKit browsers, while browsing the `TravelMethods` page.
**Problem:** in Webkit browsers, the text labels in the Travel Method buttons could not be retrieved, causing issues in the backend logic.
**Fix:** use `e.currentTarget.textContent` to retrieve text in travel method buttons, instead of `e.target.innerText`
- verify that user can select Travel Method buttons in the `TravelMethod page on:
- a iphone browser (safari/chrome/firefox), 
- and an android browser
- a desktop browser

fix bug in iOS/WebKit browsers for TravelMethod page

---

utils/dbApi.js

This PR fixes an bug that was observed in Chrome browser on iphone 6s, during survey response submission (ie, when the 'Submit' button was clicked on the `Department` page).
**Problem**: in the Chrome browser on an iphone, the following error message was displayed when the 'Submit' button was clicked on the `Department` page:
```
RangeError: timeZoneName must be "short" or "long"
```
**Fix**: follow advise in error message - use `timeZoneName: "short"` for datestamp that is sent with form submission
- Please describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce. 
- If necessary, please also list any relevant details for your test setup/configuration
- verify that `RangeError` error message does not appear during survey response submission (ie, …

fix bug in iphone chrome browsers. shows `RangeError: timeZoneName must be "short" or "long"` error during form submission

---

components/ResultsPageComponents/DownloadResults/DownloadResults.jsx
components/ResultsPageComponents/WorkArrangement/WorkArrangement.jsx

This PR addresses the warning messages that appear on the console while viewing results page:
```
Warning: React does not recognize the `lineHight` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `linehight` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
...
Warning: React does not recognize the `maxWidth` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `maxwidth` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
test the changes locally, and confirm that the warning messages no longer appear when view the results page locally. 
Make sure the following …

fix minor updates to silence the warning messages that appears on the console

---

components/ResultsPageComponents/SharedComponents/ContentStyles.jsx
components/ResultsPageComponents/SharedComponents/ResultContentSection.jsx
pages/results.js

Implemented light and dark backgrounds for the "Results" page
Designers have specified an 88px padding on left and right.
The Results page uses `<Layout>` which has a configuration of  `px={5}` = 1.25rem = 20px.
I added a `<Box>` with padding `px="68px"` with a child component with shaded/clear background.. 
20px + 68px = 88px.
Designers have also specified a gap between sections. Since no values were given, I have set the value to be `py={5}`, meaning there is a gap of 40px between sections. This has been set at every section, which gives us the ability to change quicky should there be an updated design.
https://codeforaustralia.slack.com/archives/C01DALXS62K/p1659504023077409
The Results page should have sections with light and dark backgrounds as shown below:
(note: dotted lines serve …

implement light and shaded backgrounds to the Results page

---

pages/results.js

This PR removes the placeholder images in the last 2 sections of results page.
The last 2 sections will be omitted from the first release of results page.
The desktop view of results page should look like the screen shot below:
- have not fixed any other layout issues in this PR

remove placeholder images for the last 2 sections of results page

---

components/ResultsPageComponents/CommuteDays/CommuteDaysColumnChart.jsx
components/ResultsPageComponents/CommuteDistanceDistribution/CommuteDistanceDistributionChart.jsx
components/ResultsPageComponents/DistanceTravelledMode/DistanceTravelledModeChart.jsx
components/ResultsPageComponents/SurveyOverview/SurveyOverview.jsx
components/ResultsPageComponents/TopThree/TopThree.jsx
components/ResultsPageComponents/TopThree/TopThreeBarChart.jsx
components/ResultsPageComponents/TripCountAndTravelMethods/PieChart.jsx

This PR removes the `highcharts.com` credits text from **all** the charts in the results page:
This PR also removes a couple of `console.log` statements from the codebase.

Remove highcharts credits

---

components/ResultsPageComponents/WorkArrangement/WorkArrangement.jsx

This PR updates the text content for the "work arrangement" section of the results page, to match the text content set forth in the [final figma design](https://www.figma.com/file/DEa98hc9qYB0meam2wtOau/Delta-D?node-id=2921%3A42965) (see screenshot below):
Ensure the text in 'work arrangement' section of results page is aligned with figma design:
- font settings has not been changed
- UI layout of this section has not been changed

update text in "work arrangement" section of results page

---

components/ResultsPageComponents/CommuteDays/CommuteDays.jsx
components/ResultsPageComponents/CommuteDays/CommuteDaysColumnChart.jsx

- Edited chart description to match [Figma](https://www.figma.com/file/DEa98hc9qYB0meam2wtOau/Delta-D?node-id=2921%3A42962) design
- Changed y-axis label to "% of staff who commuted"
- Changed chart title to fit colours in design
- Changed bottom description to hide the blue dot and display just the text
- Edited layout to suit mobile view
Text and chart should be left-justified in desktop view:
(_Distribution of commute_ distance chart included for reference)
<br><br>
Text and chart should be centre in mobile view:
(_Distribution of commute_ distance chart included for reference)

Travelling to Work Days - chart and section layout changes

---

components/ResultsPageComponents/CommuteDistanceDistribution/CommuteDistanceDistributionChart.jsx

Removed duplicate "km" units in x-axis values
There should be no duplicated "km" units in x-axis values:

Distribution of Commute distance - removed duplicate 'km' units in x-axis values

---

components/ResultsPageComponents/DistanceTravelledMode/DistanceTravelledMode.jsx

Mobile layout for travel method icons in "Distance travelled by mode" section
Fixes to the formatting of the text and icons header in the _Distance travelled by mode of transport_ section of the _Results_ page
Layout for icons and text should display as follows:
Desktop view:
Mobile view:

"Distance travelled by mode" section - layout for icons section

---

components/ResultsPageComponents/TripCountAndTravelMethods/PieChart.jsx
components/ResultsPageComponents/TripCountAndTravelMethods/PieChartComponent.jsx
components/ResultsPageComponents/TripCountAndTravelMethods/TripCountAndTravelMethods.jsx

this PR updates the colors used in the donut charts (in the 'Trip count and Travel Methods' section of results page) to match the color scheme of the page, and align with the [final figma design](https://www.figma.com/file/DEa98hc9qYB0meam2wtOau/Delta-D?node-id=2921%3A42965) (see screenshot below):
https://trello.com/c/T943YdMY
check in the preview deployment that the color scheme of donut chart matches that of the figma design:

Update color scheme for donut charts 

---

pages/howWeCalculate.js

Small fixes to the How We Calculate Page:
1. Fix the responsiveness of copyright reference block
Before:
After: 
2. Fix the border radius for contents header:
Before: 
After:

fix responsiveness for copyright reference block

---

next.config.js
package-lock.json
package.json

fixes #227 
* the bug reported in #227 was due to outdated SSL libraries in the version of webpack used in nextJS v11. this PR upgrades nextJS to v12
* also updated the following packages to address some security issues:
* svgr
* reactJS to v18
#227 
1. install and use the latest lts version using nvm:
```
nvm install v18.12.1
nvm use
```
2. remove `node_modules/` folder, and run `npm install`
3. run `npm run dev`
4. Should no longer see error message reported in #227 

bug fix for issue #227
